select 
    u.user_id,
    {{ dbt_utils.generate_surrogate_key(["u.user_id"]) }} as user_sk,
    u.user_first_name,
    u.user_last_name,
    u.user_email,
    u.user_age,
    u.user_gender,
    u.user_state,
    u.user_street_address,
    u.user_postal_code,
    u.user_city,
    u.user_country,
    u.user_traffic_source,
    u.user_longitude,
    u.user_latitude,
    u.user_created_at,
    coalesce(o.completed_orders, 0) as completed_orders,
    o.last_order_completed_at,
    coalesce(o.returned_orders, 0) as returned_orders,
    o.last_order_returned_at,
    coalesce(o.cancelled_orders, 0) as cancelled_orders,
    o.last_order_cancelled_at,
    coalesce(o.total_orders, 0) as total_orders,
    o.first_order_at,
    o.last_order_at,
    coalesce(o.user_ltv, 0) as user_ltv,
    coalesce(o.user_items_purchased, 0) as user_items_purchased,
    coalesce(o.is_active_customer, FALSE) as is_active_customer
from {{ ref("stg_the_look__users") }} u
left join {{ ref("inter_user_orders") }} o 
    on u.user_id = o.user_id